
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://odwvlzlmxzwtfbsjnsym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9kd3ZsemxteHp3dGZic2puc3ltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjcxNzk4NTgsImV4cCI6MjA0Mjc1NTg1OH0.ecHBWgDFn-ULO5GTsS7otY69VIfC2fLca_65I1JL_Xc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    storage: localStorage
  }
});
